### ISSUE TITLE
Precompiled APKs cannot run on Android 10 and below systems

### ISSUE THREAD

**Issue by bohonghuang** [Gleefre/hello-alien#1] opened 2023-04-19 15:35 UTC
Hello! First of all, thank you for providing a way to run SBCL in native Android applications, but recently I have tested the compatibility of the precompiled application you provided on multiple ARM64 Android devices (including Android 7, 9, 10, and 13). In my testing, I found that it only works properly on Android 13, and cannot run on other versions of Android. Specifically, after pressing the button, the application freezes. 

![Screenshot_20230419-233808](https://user-images.githubusercontent.com/11132087/233128126-946eee65-6d56-4397-88fa-82e106380859.png)

When debugging with ADB, the following repeated logcat output will appear:

```
04-19 23:09:35.377  3592  3964 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=ch.deletescape.lawnchair.ci/ch.deletescape.lawnchair.LawnchairLauncher (has extras)} from uid 1000
04-19 23:09:35.890  3592  3963 W ActivityManager: Activity pause timeout for ActivityRecord{b55a89d u0 hi.to.alien/.HelloActivity t142}
--------- beginning of main
04-19 23:09:37.368  9612  9612 E SBCL    : Received signal 2043446512 @ 0 in non-lisp tid -1, resignaling to a lisp thread.
04-19 23:09:37.368  9612  9612 E SBCL    :  in SBCL pid 9612 tid 9612
04-19 23:09:37.368  9612  9612 E SBCL    : Received signal 2043441536 @ 0 in non-lisp tid -1, resignaling to a lisp thread.
04-19 23:09:37.368  9612  9612 E SBCL    :  in SBCL pid 9612 tid 9612
04-19 23:09:37.368  9612  9612 E SBCL    : Received signal 2043436560 @ 0 in non-lisp tid -1, resignaling to a lisp thread.
04-19 23:09:37.368  9612  9612 E SBCL    :  in SBCL pid 9612 tid 9612
...
```

**Comment by Gleefre** [comment] 2023-04-19 17:20
Hello!
Thanks for letting me know. It might have something to do with the fact that I compiled SBCL on Android 11, but I'm not sure.

**Comment by Gleefre** [comment] 2023-04-20 22:02
Hello!

I have added an `*init-hook*` that logs backtrace, which you can see with `adb logcat`. Since there were messages from SBCL, I assume that the error would be captured (and signaled further, but that's not the point).

Could you please try these new apks?
https://github.com/Gleefre/hello-alien/raw/main/artifacts/hello-alien-debug-with-logs-on-crash.apk
https://github.com/Gleefre/hello-alien/raw/main/artifacts/hello-alien-debug-with-logs-on-crash-and-new-sbcl.apk

**Comment by bohonghuang** [comment] 2023-04-21 00:08
After testing, it seems that the two APKs you newly uploaded only output the following two lines besides anything else:

```
04-21 07:43:34.726  9968  9968 V ALIEN   : Core file is at /data/app/hi.to.alien-mz_-cwZR2hs1pBW19K10sw==/lib/arm64/libcore.so
04-21 07:43:35.009  9968  9968 V ALIEN   : Lisp initialised by core /data/app/hi.to.alien-mz_-cwZR2hs1pBW19K10sw==/lib/arm64/libcore.so
```

**Comment by Gleefre** [comment] 2023-04-21 00:17
Hm, and the application freezes?.. It seems that SBCL loads just fine.

**Comment by bohonghuang** [comment] 2023-04-21 00:19
Yes, the application is still frozen as before.

**Comment by bohonghuang** [comment] 2023-04-21 11:00
I'm trying to tackle this problem myself, but the following errors occurred in `make-sbcl.sh`:

```
/opt/android-ndk//toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -c -I. -g -Wall -Wundef -Wsign-compare -Wpointer-arith -O3 -march=armv8 -std=gnu99 -Wunused-parameter -fno-omit-frame-pointer -momit-leaf-frame-pointer arm64-assem.S -o arm64-assem.pic.o
/opt/android-ndk//toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -fPIC -c -I. -g -Wall -Wundef -Wsign-compare -Wpointer-arith -O3 -march=armv8 -std=gnu99 -Wunused-parameter -fno-omit-frame-pointer -momit-leaf-frame-pointer ../../tlsf-bsd/tlsf/tlsf.c -o ../../tlsf-bsd/tlsf/tlsf.pic.o
/opt/android-ndk//toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -shared -o libsbcl.so alloc.pic.o arena.pic.o backtrace.pic.o breakpoint.pic.o coalesce.pic.o coreparse.pic.o dynbind.pic.o funcall.pic.o gc-common.pic.o globals.pic.o hopscotch.pic.o interr.pic.o interrupt.pic.o largefile.pic.o main.pic.o math.pic.o monitor.pic.o murmur_hash.pic.o os-common.pic.o parse.pic.o print.pic.o regnames.pic.o runtime.pic.o safepoint.pic.o save.pic.o sc-offset.pic.o search.pic.o stringspace.pic.o thread.pic.o time.pic.o validate.pic.o var-io.pic.o vars.pic.o wrap.pic.o run-program.pic.o sprof.pic.o arm64-arch.pic.o linux-os.pic.o linux-mman.pic.o arm64-linux-os.pic.o android-os.pic.o arm64-android-os.pic.o fullcgc.pic.o gencgc.pic.o traceroot.pic.o arm64-assem.pic.o ../../tlsf-bsd/tlsf/tlsf.pic.o -ldl  -lm -Wl,-soname,libsbcl.so
ld: error: relocation R_AARCH64_LD_PREL_LO19 cannot be used against symbol 'current_thread'; recompile with -fPIC
>>> defined in thread.pic.o
>>> referenced by arm64-assem.S:153
>>>               arm64-assem.pic.o:(call_into_lisp)
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm not sure how is the error related to this issue.

**Comment by Gleefre** [comment] 2023-04-21 11:01
Hello! Which NDK version do you use? Unfortunately libscbl.so fails to build with NDK 22 and higher

**Comment by bohonghuang** [comment] 2023-04-21 11:14
I'm using NDK 25, and I will try recompiling it with NDK 21. Thanks.

**Comment by bohonghuang** [comment] 2023-04-21 11:51
I have successfully compiled SBCL and can launch it from the ADB shell, but the application still freezes when clicking buttons. By debugging, it can be seen that the application is stuck in the `getAlien` function.

**Comment by Gleefre** [comment] 2023-04-21 12:05
Hm, you can try to modify it & recompile?

The lisp side is in `lisp/alien.lisp`. Try replacing
```lisp
(define-alien-callable hello sb-alien:c-string ()
  (format nil "Hello alien world! [clicks: ~a]"
          (incf *clicks*)))
```
with something like
```lisp
(define-alien-callable hello sb-alien:c-string ()
  "HELLO")
```
?

**Comment by Gleefre** [comment] 2023-04-21 12:08
There might be a problem with C wrapper... I think I got crashes at first when I tried to return long strings / strings with newlines from lisp :/

**Comment by bohonghuang** [comment] 2023-04-21 12:20
Unfortunately, it doesn't work.

**Comment by Gleefre** [comment] 2023-04-21 12:21
Hm, you might try to run `lldb` attached to application process.

**Comment by Gleefre** [comment] 2023-04-21 12:27
Instructions (if needed):
1) Find `lldb-server` in you NDK folder
```
find $NDK -name lldb-server
```
It will result in several programs, one for each architecture.
Copy it to your device:
adb push /path/to/lldb /data/local/tmp
2)
Run lldb server in application profile:
```
run-as hi.to.alien cp /data/local/tmp/lldb-server /data/data/hi.to.alien/
run-as hi.to.alien ls /data/data/hi.to.alien/
run-as hi.to.alien sh -c "/data/data/hi.to.alien/lldb-server platform --server --listen unix-abstract:///data/data/hi.to.alien/debug.socket"
```
3) Install `lldb` and run from command line.
Then attach it to the app process (you need to run application first):
```
$ lldb
(lldb) platform select remote-android
(lldb) platform connect unix-abstract-connect:///data/data/hi.to.alien/debug.socket
(lldb) attach PID
```
PID must be the pid of your application, you can get it from adb shell with `pidof` or `ps` commands.
```
adb shell pidof hi.to.alien
5562
```
3) Configure it to skip GC signals:
```
(lldb) process handle SIGSEGV -n true -p true -s false
```
continue the process with
```
(lldb) c
```

And now click the button and see the result...

**Comment by bohonghuang** [comment] 2023-04-21 12:46
It can be confirmed that SBCL has been successfully initialized, and calling C functions from SBCL works fine (in `*init-hook*`), but calling SBCL functions from C doesn't work.

**Comment by Gleefre** [comment] 2023-04-21 12:50
Is there any output from `lldb`?

**Comment by Gleefre** [comment] 2023-04-21 12:56
There is a problem with uncaptured stdout, so you can't run lisp_backtrace(20) and get any output.

You can checkout to the new branch `with-backtrace-to-log` of my fork of sbcl, I have redirected output from lisp_backtrace to android log on arm64, (I hope that successfully),

Recompile SBCL and application. You need to recompile shared libraries only: run
```
# checkout
(cd sbcl-arm64-v8a ; git checkout with-backtrace-to-log )
# libsbcl.so
(cd sbcl-arm64-v8a ; ./make-shared-library.sh )
cp sbcl-arm64-v8a/src/runtime/libsbcl.so libs/arm64-v8a/libsbcl.so
# libhello-alien.so
./make-c.sh
# app
./gradlew assembleDebug  # or installDebug
```
And then from lldb, after the crash (if any):
```
(lldb) expr (void) lisp_backtrace(20)
```
which should print the backtrace to log.

**Comment by bohonghuang** [comment] 2023-04-21 13:20
I can't get the backtrace, since SBCL doesn't crash when `getAlien` is called from Java. The following code will keep running even when the applications freezes:

``` lisp
(defun print-from-lisp (n)
  (sb-alien:alien-funcall (sb-alien:extern-alien "print_from_lisp" (sb-alien:function sb-alien:void sb-alien:int)) n))

(push (lambda ()
        (sb-alien:load-shared-object "libhello-alien.so")
        (sb-thread:make-thread (lambda ()
                                 (loop :for i :from 0
                                       :do (print-from-lisp i)
                                           (sleep 1)))))
      *init-hooks*)
```

**Comment by Gleefre** [comment] 2023-04-21 13:21
I see. I tried to fix C wrapper, can you check out the `try-again` branch?
I added a temporary variable that C will copy returned from lisp string before passing it to java.

**Comment by Gleefre** [comment] 2023-04-21 13:26
> SBCL doesn't crash

That's cool! It means that the problem is on C / Java side..

**Comment by bohonghuang** [comment] 2023-04-21 13:30
> I see. I tried to fix C wrapper, can you check out the `try-again` branch? I added a temporary variable that C will copy returned from lisp string before passing it to java.

OK. I will try it later, but it's worth mentioning that it still freezes when I change the return value of the callback to a simple integer.

**Comment by Gleefre** [comment] 2023-04-21 13:43
Hm, that sounds weird. I'll think about it and I'll try to find an old android device...

Thanks for testing! Good luck with further debugging :)

**Comment by bohonghuang** [comment] 2023-04-21 13:51
You're welcome. I believe this project is of significant importance to the Lisp ecosystem. Thank you for your help and have a great day.

**Comment by Gleefre** [comment] 2023-04-21 14:02
Thanks! You too have a great day! :black_cat:

**Comment by bohonghuang** [comment] 2023-04-21 16:43
An interesting observation is that SBCL seems unable to set the function pointer of `hello` correctly in the JNI address space. Passing the function pointer and calling it immediately works, but setting a global variable to enable JNI to call SBCL functions still does not work.

The following code:
- `alien.c`
```c
#include <jni.h>
#include <string.h>
#include <android/log.h>

#define LOG_TAG   "ALIEN"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

extern int initialize_lisp(int argc, char **argv);

__attribute__((visibility("default"))) char* (*hello)();
const char *(*hello_fp)(int);

void setup_fp(const char *(*fp)(int)) { /* This function is called from Lisp */
  LOGD("%s", fp(1));            /* Sucessfully call fp */
  hello_fp = fp;
  LOGD("setup_fp: hello_fp_addr: %llu", (unsigned long long)&hello_fp);
  LOGD("setup_fp: hello_fp: %llu", (unsigned long long)hello_fp);
  LOGD("setup_fp: hello_addr: %llu", (unsigned long long)&hello);
  LOGD("setup_fp: hello: %llu", (unsigned long long)hello);
}

int init(char* core) {
  char *init_args[] = {"", "--core", core, "--noinform", "--disable-ldb"};
  if (initialize_lisp(5, init_args) != 0) return -1;
  LOGD("init: hello_fp_addr: %llu", (unsigned long long)&hello_fp);
  LOGD("init: hello_fp: %llu", (unsigned long long)hello_fp);
  LOGD("init: hello_addr: %llu", (unsigned long long)&hello);
  LOGD("init: hello: %llu", (unsigned long long)hello);
  return 0;
}

JNIEXPORT void JNICALL
Java_hi_to_alien_HelloActivity_initLisp(JNIEnv *env, jobject thiz, jstring path) {
  char* core_filename = strdup((*env)->GetStringUTFChars(env, path, NULL));
  init(core_filename);
}

JNIEXPORT jstring JNICALL
Java_hi_to_alien_HelloActivity_getAlien(JNIEnv *env, jobject thiz) {
  LOGD("getAlien: hello_fp_addr: %llu", (unsigned long long)&hello_fp);
  LOGD("getAlien: hello_fp: %llu", (unsigned long long)hello_fp);
  LOGD("getAlien: hello_addr: %llu", (unsigned long long)&hello);
  LOGD("getAlien: hello: %llu", (unsigned long long)hello);
  hello_fp(1);
  return (*env)->NewStringUTF(env, hello_fp(1));
}
```
- `alien.lisp`
```lisp
(defparameter *clicks* 0)

(define-alien-callable hello sb-alien:c-string ()
  (format nil "Hello alien world! [clicks: ~a]" (incf *clicks*)))

;; SBCL will search for HELLO function in main program by default
;; Main program is Java program, so we need to load
;; the libhello-alien.so library at the startup.
(push (lambda ()
        (sb-alien:load-shared-object "libhello-alien.so")
        (sb-alien:alien-funcall
         (sb-alien:extern-alien
          "setup_fp" (sb-alien:function sb-alien:void sb-alien:unsigned-long-long))
         (sb-sys:sap-int (sb-alien:alien-sap
                          (sb-alien::alien-lambda (:cdecl sb-alien:c-string) ((i sb-alien:int))
                            (format nil "Hello alien world! [clicks: ~a]" (incf *clicks* i)))))))
      *init-hooks*)

(save-lisp-and-die "libcore.so" :callable-exports '(hello)
                                #+sb-core-compression :compression
                                #+sb-core-compression t)
```

produced the following output:

```
2023-04-22 00:16:31.121   717-717   ALIEN                   hi.to.alien                          V  Core file is at /data/app/hi.to.alien-mCPXRz_sHwwcrTvI6UBflQ==/lib/arm64/libcore.so
2023-04-22 00:16:31.143   717-717   ALIEN                   hi.to.alien                          D  Hello alien world! [clicks: 1]
2023-04-22 00:16:31.143   717-717   ALIEN                   hi.to.alien                          D  setup_fp: hello_fp_addr: 531618488320
2023-04-22 00:16:31.143   717-717   ALIEN                   hi.to.alien                          D  setup_fp: hello_fp: 4027584672
2023-04-22 00:16:31.143   717-717   ALIEN                   hi.to.alien                          D  setup_fp: hello_addr: 531618488328
2023-04-22 00:16:31.143   717-717   ALIEN                   hi.to.alien                          D  setup_fp: hello: 0
2023-04-22 00:16:31.144   717-717   ALIEN                   hi.to.alien                          D  init: hello_fp_addr: 531618664448
2023-04-22 00:16:31.144   717-717   ALIEN                   hi.to.alien                          D  init: hello_fp: 0
2023-04-22 00:16:31.144   717-717   ALIEN                   hi.to.alien                          D  init: hello_addr: 531618664456
2023-04-22 00:16:31.144   717-717   ALIEN                   hi.to.alien                          D  init: hello: 0
2023-04-22 00:16:31.144   717-717   ALIEN                   hi.to.alien                          V  Lisp initialised by core /data/app/hi.to.alien-mCPXRz_sHwwcrTvI6UBflQ==/lib/arm64/libcore.so
2023-04-22 00:16:31.144   717-717   ALIEN                   hi.to.alien                          D  getAlien: hello_fp_addr: 531618664448
2023-04-22 00:16:31.144   717-717   ALIEN                   hi.to.alien                          D  getAlien: hello_fp: 0
2023-04-22 00:16:31.144   717-717   ALIEN                   hi.to.alien                          D  getAlien: hello_addr: 531618664456
2023-04-22 00:16:31.144   717-717   ALIEN                   hi.to.alien                          D  getAlien: hello: 0
```

I speculate that `sb-alien:load-shared-object` loaded the dynamic shared library `libhello-alien.so` twice for some unknown reason, resulting in two copies of the library in memory. SBCL always modifies the copy it loaded itself, which causes the function pointer on the JNI side to remain uninitialized, i.e., NULL. Calling it as a function pointer is an undefined behavior and on Android, this results in the current thread getting stuck in a loop, causing the application to freeze. I have no idea why this kind of duplication loading happens. The result of `getpid` indicates that they are always in the same process.

**Comment by Gleefre** [comment] 2023-04-21 18:16
Hm, I think this can be fixed by using `dlsym(RTLD_DEFAULT, ...)`. I gonna modify sbcl a bit again and I'll write you back when it's done.

**Comment by Gleefre** [comment] 2023-04-22 07:34
Hello! I have some progress!

At first it didn't work, but according to [this thread](https://github.com/android/ndk/issues/1244), the `libhello-alien.so` needs to be compiled with `-Wl,-z,global` flag.

I did so in [this branch](https://github.com/Gleefre/hello-alien/tree/with-rtld-default-and-c-flag). It also fetches `with-dlsym-default` branch of my sbcl fork. With this new branch of sbcl it doesn't need to load shared library at startup, because it when it can't find a foreign symbol in loaded shared libraries it tries to find it with `dlsym(RTLD_DEFAULT, name)`.

I have compiled [an apk](https://github.com/Gleefre/hello-alien/raw/with-rtld-default-and-c-flag/artifacts/hello-alien-fixed-p.apk) too, so you can check it without recompiling everything :)

Hopefully it will work!

**Comment by bohonghuang** [comment] 2023-04-22 08:48
Hi! I just tried your latest APK file and it works well on Android 13, but it crashes directly when I press the button on devices running Android 10 or below, and SBCL does not finish initializing. My guess is that `hello-alien.so` is still not loaded for SBCL, causing it to crash when setting up the global function pointer `hello`.

**Comment by Gleefre** [comment] 2023-04-22 08:50
That's sad :(

Could you try recompiling your previous code with `-Wl,-z,global` flag?

**Comment by Gleefre** [comment] 2023-04-22 08:53
I left out the `load-shared-library` from lisp code, since it was able to find needed symbol directly with `dlsym(RTLD_DEFAULT, symbol)`. Maybe this is not enough though.

**Comment by bohonghuang** [comment] 2023-04-22 09:00
> I left out the `load-shared-library` from lisp code, since it was able to find needed symbol directly with `dlsym(RTLD_DEFAULT, symbol)`. Maybe this is not enough though.

I thought that `load-shared-library` was unnecessary before, but I found that removing it caused the program to crash just like your newly compiled APK file. SBCL seems to be unable to know that `hello-alien.so` has been loaded and obtain the symbol address. I think this is also the case for the issue of duplicate loading that occurred earlier.

**Comment by Gleefre** [comment] 2023-04-22 09:03
I just recompiled it with `open-shared-library` and pushed it: [apk](https://github.com/Gleefre/hello-alien/raw/with-rtld-default-and-c-flag/artifacts/hello-alien-2-fixed-p.apk)

**Comment by Gleefre** [comment] 2023-04-22 09:06
> but I found that removing it caused the program to crash

Yes, it was necessary because SBCL didn't search the alien symbol with `dlsym(RTLD_DEFAUL, name)`, but I added it in a new branch of my fork.

I think that if it can't find it it means that `libhello-alien.so` doesn't get loaded into global address space, but is loaded somewhere in the java memory. I think we can solve it by creating a second layer of C wrapper that doesn't link against `libhello-alien.so` but loads it with `dlopen` at runtime.

**Comment by bohonghuang** [comment] 2023-04-22 09:08
> I just recompiled it with `open-shared-library` and pushed it: [apk](https://github.com/Gleefre/hello-alien/raw/with-rtld-default-and-c-flag/artifacts/hello-alien-2-fixed-p.apk)

The application freezes as before :(

**Comment by Gleefre** [comment] 2023-04-22 09:09
Ok, thanks for testing!
It is time to try plan B! :black_cat:

**Comment by Gleefre** [comment] 2023-04-22 10:55
I have got something working (branch `2-wrappers`, [apk](https://github.com/Gleefre/hello-alien/raw/2-wrappers/artifacts/hello-alien-debug-2-wrap.apk)). It is not very polished, but should work.

**Comment by bohonghuang** [comment] 2023-04-22 11:04
> 

Still, it freezes when the button is clicked :/

**Comment by Gleefre** [comment] 2023-04-22 11:20
That is sad :(

**Comment by bohonghuang** [comment] 2023-04-22 13:17
It seems possible to reproduce the issue in emulator (with x86-64 system image). The application runs properly on Android 11 but crashes on Android 10.

![android11](https://user-images.githubusercontent.com/11132087/233787263-01fd6105-e124-46e3-aac3-119aa02c4a5b.png)

![android10](https://user-images.githubusercontent.com/11132087/233787361-be41c1dc-3458-4632-a926-977e54412021.png)

**Comment by Gleefre** [comment] 2023-04-22 13:39
That's good news, I'll try to debug it on emulator then.
I tried to run arm64 emulator before which is not supported...

**Comment by Gleefre** [comment] 2023-04-22 14:48
I got it working.

We need only one wrapper, but I need to change sbcl a bit again. I think easiest thing to do is to get handle to the `libhello-alien.so` from itself (in this case `dlopen` does the right thing), set it to some internal value in sbcl, get it from app and manually add shared library with the given handle.

It seems to be easy.

**Comment by Gleefre** [comment] 2023-04-22 16:53
I built `.apk` and it seems to work on some old android emulator.
Please see`fix-old-android` branch ([apk](https://github.com/Gleefre/hello-alien/raw/fix-old-android/artifacts/hello-alien-debug.apk))

I hope it will finally work!

**Comment by bohonghuang** [comment] 2023-04-22 17:53
Wow, that works :)

**Comment by Gleefre** [comment] 2023-04-22 17:54
Yay!

**Comment by bohonghuang** [comment] 2023-04-22 18:01
Thank you for your effort, Gleefre.

**Closed as completed** 2023-04-22 18:01 UTC
